# Generated by Django 3.0.6 on 2020-05-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(db_column='name', max_length=20, verbose_name='kid name')),
                ('age', models.IntegerField(db_column='age', verbose_name='kid age')),
                ('sex', models.CharField(db_column='sex', max_length=10, verbose_name='kid sex')),
            ],
            options={
                'db_table': 'kid',
            },
        ),
    ]
